FROM python:3.11-slim AS build

# Set environment variables to optimize pip
ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on

# Install system dependencies
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    poppler-utils \
    libglib2.0-0 \
    libnss3 \
    #libgconf-2-4 \
    libfontconfig1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# stage 2
# Stage 2: Production stage
FROM python:3.11-slim 

# Set the working directory
WORKDIR /app


# Copy the dependencies from the build stage
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin

# copy all files
COPY . .

# Expose the port the app runs on
EXPOSE 8015

# Command to run the application
# gunicorn -w 4 -b 0.0.0.0:8015 app:app &
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8015", "app:app"]