name: Emotion service CI

on:
  push:
    branches: [ main ]
    paths:
    - "backend/emotion/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-emotion-${{ hashFiles('backend/emotion/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-emotion-

    - name: Install dependencies
      working-directory: backend/emotion
      run: pip install -r requirements.txt
    
    - name: Run Unit Tests
      working-directory: backend/emotion
      env:
        PYTHONPATH: backend/emotion
      run: |
        pip install pytest pytest-cov pytest-asyncio
        PYTHONPATH=$(pwd) pytest