name: Fact-check CI

on:
  push:
    branches: [ main ]
    paths:
    - "backend/fact-check/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-factcheck-${{ hashFiles('backend/fact-check/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-factcheck-

    - name: Install dependencies
      working-directory: backend/fact-check
      run: pip install -r requirements.txt
    
    - name: Run Unit Tests
      working-directory: backend/fact-check
      env:
        PYTHONPATH: backend/fact-check
        API_KEY: ${{ secrets.API_KEY || 'PLACEHOLDER' }}
        API_KEYDS: ${{ secrets.API_KEYDS || 'PLACEHOLDER' }}
      run: |
        pip install pytest pytest-cov pytest-asyncio
        PYTHONPATH=$(pwd) pytest