outlet_geography = {
    # United States
    "Fox News Digital": "USA",
    "CNN Digital": "USA",
    "NBC News Digital": "USA",
    "USA TODAY": "USA",
    "Washington Examiner": "USA",
    "HuffPost": "USA",
    "Townhall": "USA",
    "NPR (Online News)": "USA",
    "Fox Business": "USA",
    "Breitbart News": "USA",
    "CBS News (Online)": "USA",
    "Forbes": "USA",
    "ABC News (Online)": "USA",
    "Daily Beast": "USA",
    "The Daily Wire": "USA",
    "CBN": "USA",
    "New York Post (News)": "USA",
    "The Blaze": "USA",
    "Newsmax": "USA",
    "AP News": "USA",
    "Associated Press": "USA",
    "MSNBC": "USA",
    "Axios": "USA",
    "Reuters": "UK",  # International but UK-based
    "WSJ": "USA",
    "Wall Street Journal": "USA",
    "Time": "USA",
    "The Atlantic": "USA",
    "The Washington Post (Online)": "USA",
    "Washington Post": "USA",
    "The Root": "USA",
    "Slate": "USA",
    "Salon": "USA",
    "Reason": "USA",
    "National Review": "USA",
    "The National Interest": "USA",
    "RedState": "USA",
    "Vox": "USA",
    "Politico": "USA",
    "The Hill": "USA",
    "New York Times (Online News)": "USA",
    "New York Times": "USA",
    "Los Angeles Times": "USA",
    "Chicago Tribune": "USA",
    "Boston Globe": "USA",
    "The Guardian": "UK",
    "BBC News": "UK",
    "Daily Mail": "UK",
    "The Telegraph": "UK",
    "The Independent": "UK",
    "The Sun": "UK",
    "Sky News": "UK",
    "Al Jazeera": "Qatar",
    "DW (English)": "Germany",
    "France 24": "France",
    "Euronews": "Europe",
    "The Irish Times": "Ireland",
    "CBC News": "Canada",
    "CTV News": "Canada",
    "Toronto Star": "Canada",
    "The Globe and Mail": "Canada",
    "Sydney Morning Herald": "Australia",
    "ABC News (Australian)": "Australia",
    "The Australian": "Australia",
    "News Corp Australia": "Australia",
    "Stuff.co.nz": "New Zealand",
    "NZ Herald": "New Zealand",
    "India Today": "India",
    "Times of India": "India",
    "The Hindu": "India",
    "NDTV": "India",
    "Business Insider": "USA",
    "Quartz": "USA",
    "Insider": "USA",
    "The Verge": "USA",
    "Wired": "USA",
    "Mashable": "USA",
    "TechCrunch": "USA",
    "CNBC": "USA",
    "MarketWatch": "USA",
    "Yahoo News": "USA",
    "The Daily": "USA",
    "Newsweek": "USA",
    "U.S. News & World Report": "USA",
    "Daily Caller": "USA",
    "Epoch Times": "USA",
    "The Federalist": "USA",
    "Conservative Review": "USA",
    "Free Beacon": "USA",
    "Examiner.com": "USA",
    "WND": "USA",
    "Breitbart": "USA",
    "Red State": "USA",
    "The American Conservative": "USA",
    "Real Clear Politics": "USA",
    "Heritage": "USA",
    "American Enterprise Institute": "USA",
    "Center for American Progress": "USA",
    "Think Progress": "USA",
    "Media Matters": "USA",
    "CNN": "USA",
    "MSNBC Digital": "USA",
    "Fox": "USA",
    "ABC": "USA",
    "CBS": "USA",
}
